version: '2.1'
services:
  function:
    image: ${DOCKER_REGISTRY-}pocfunctions
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      LD_LIBRARY_PATH: "/home/site/wwwroot/bin/runtimes/linux-x64/native"
      broker_list: "kafka:9092"
      topic_name: "Wng1"
      CONSUMER_GROUP: "sampleGroup"
      ApplicationInsights_InstrumentationKey: "8a86d23f-ecc4-4f0c-a78a-ca6ed18de4cb"
    depends_on:
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKERHOST:-0.0.0.0}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  default:
    external:
      name: kafka-net
